version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=pablitoclavounclavito"
    expose:
      - "5432"
    ports:
      - "5432:5432"